logging:
  level: DEBUG
  file: 17_cutlass.log

device:
  id: 0

tutorial:
  name: "cutlass"
  M: 4096
  N: 4096
  K: 4096
  alpha: 1.0
  beta: 0.0
  # CUTLASS threadblock tile
  tile_M: 128
  tile_N: 256
  tile_K: 32
  num_iterations: 20
